using ArgParse
using Plots
using StructArrays
using PM3
using Serialization

function parse_plot_args()
    s = ArgParseSettings(description = "Plot a 2D slice of the PM3 simulation")

    @add_arg_table! s begin
        "--input"
            help = "Input data file (.jls) generated by run.jl"
            arg_type = String
            default = "final_state.jls"
        "--slice_center"
            help = "Z-coordinate center of the slice"
            arg_type = Float64
            default = 32.0
        "--thickness"
            help = "Thickness of the slice"
            arg_type = Float64
            default = 6.0
        "--out"
            help = "Output image filename"
            arg_type = String
            default = "cosmic_web_slice.png"
    end
    return parse_args(s)
end

function main()
    args = parse_plot_args()
    
    println("Loading data from $(args["input"])...")
    particles, N_cells = deserialize(args["input"])

    slice_center = args["slice_center"]
    thickness = args["thickness"]

    println("Extracting 2D slice at Z = $slice_center ± $(thickness/2)...")
    in_slice = @. abs(particles.z - slice_center) < (thickness / 2.0)
    
    x_slice = particles.x[in_slice]
    y_slice = particles.y[in_slice]
    
    println("Found $(length(x_slice)) particles. Plotting...")
    
    p = scatter(
        x_slice, y_slice,
        markersize = 1.5,          
        markerstrokewidth = 0,     
        color = :black, 
        alpha = 0.1,               
        legend = false,            
        aspect_ratio = 1.0,        
        xlims = (0, N_cells),      
        ylims = (0, N_cells),
        framestyle = :box,
        grid = false,              
        title = "Particle Slice (Z ≈ $slice_center)",
        xlabel = "X (Code Units)",
        ylabel = "Y (Code Units)",
        dpi = 300                  
    )
    
    savefig(p, args["out"])
    println("Saved plot to $(args["out"])!")
end

main()